### ISSUE TITLE
It isn't possible to encrypt binary data !?

### ISSUE THREAD

**Issue by user163** [web-token/jwt-framework#553] opened 2024-04-10 10:08 UTC
### Version(s) affected

3.3

### Description

In [this](https://web-token.spomky-labs.com/the-components/encrypted-tokens-jwe/jwe-creation) JWE example, the following can be read as a comment on the payload: 

> The payload we want to encrypt. It MUST be a string

and indeed if the message is not a UTF-8 compatible byte sequence, an 

> InvalidArgumentException: The payload must be encoded in UTF-8

 is thrown. 

Why is there this constraint, i.e. why can't the payload be any byte sequence? In [RFC7516 JWE](https://datatracker.ietf.org/doc/html/rfc7516) this restriction does not seem to be specified. Other JWE implementations, such as [JWCrypto](https://jwcrypto.readthedocs.io/en/latest/) allow arbitrary byte sequences.

### How to reproduce

Run the [linked example](https://web-token.spomky-labs.com/the-components/encrypted-tokens-jwe/jwe-creation) and use a non-UTF-8 compliant byte sequence as payload.

### Possible Solution

The restriction to UTF-8 compatible byte sequences as payload should be removed. It should be possible to use _any_ byte sequence as payload.

### Additional Context

There is a similar (meanwhile fixed) bug, but in the context of signing _detachd_ payloads: [#491](https://github.com/web-token/jwt-framework/issues/491).

**Comment by Spomky** [comment] 2024-04-10 12:39
Hi,

This looks like a regression not covered by tests.
It will be fixed soon.

**Closed as completed** 2024-04-10 15:46 UTC
Labels: bug
